### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.mux.stats.sdk.muxstats.b

### ISSUE THREAD

**Issue by platinum7919** [muxinc/stats-sdk-exoplayer#1]
```
05-11 07:27:55.164 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.charaku.popsical.tv, PID: 14907
                                    ` java.lang.NoClassDefFoundError: com.mux.stats.sdk.muxstats.b`
                                         at com.mux.stats.sdk.muxstats.MuxStats.b(Unknown Source)
                                         at com.mux.stats.sdk.muxstats.MuxStats.<init>(Unknown Source)
```
I keep getting this error. I tried cleaning/rebuilding the project many times.

Looking at the example provided, it seems like you downloaded the exoplayer2 v2.1.1 library and using references on class that is only on that version. 

From the sample build.gradle:
```
 project.ext {
        compileSdkVersion=24
        targetSdkVersion=24
        buildToolsVersion='23.0.3'
        releaseRepoName = 'exoplayer'
        releaseUserOrg = 'google'
        releaseGroupId = 'com.google.android.exoplayer'
        releaseVersion = 'r2.1.1'
        releaseWebsite = 'https://github.com/google/ExoPlayer'
    }
```

For example, the latest exoplayer 2.1.1 the code to init the player looks like
 ```
   TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveTrackSelection.Factory(BANDWIDTH_METER);

        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);

        SimpleExoPlayer simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl(),
                drmSessionManager, extensionRendererMode);
```

Where as in 2.3.1
```
        TrackSelection.Factory videoTrackSelectionFactory =
                new AdaptiveVideoTrackSelection.Factory(BANDWIDTH_METER);
        trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);


        SimpleExoPlayer simpleExoPlayer = ExoPlayerFactory.newSimpleInstance(this, trackSelector, new DefaultLoadControl(),
                drmSessionManager, extensionRendererMode);
```

So if I use use 2.1.1 it will work
 `   compile 'com.google.android.exoplayer:exoplayer:r2.1.1'`
But if I use 2.3.1 
`    compile 'com.google.android.exoplayer:exoplayer:r2.3.1'`

The same mux.aar will return java.lang.NoClassDefFoundError error. This error is thrown from inside com.mux.stats.sdk.muxstats.MuxStats.b. 

So am I forced to use 2.1.1 if I am to integrate this SDK?

**Comment by jsanford8** [comment]
Hi @platinum7919 - I am going to take a look at this in the morning and will get back to you here.

**Comment by jsanford8** [comment]
Actually, a quick question for you: Looking [here](https://github.com/google/ExoPlayer/commit/ce5c0c18f952caa19b863345252fd267804d7e83), it seems that `AdaptiveVideoTrackSelection` class was renamed to `AdaptiveTrackSelection` in 2.4.0. 

Do you have any plans to upgrade to 2.4.0? Or are you locked on 2.3.1 for some features? Fadhli mentioned on the call that you have some special logic around audio, so I want to check with you on the version you are using and why.

**Comment by platinum7919** [comment]
Hi Jsanford

Yes, we can migrate to 2.4.0 (actually we already have the code for it).

Regarding the special audio logic, we only have one special request. I assume that mux stats will try to capture exception through ExoPlayer.EventListener.onPlayerError, if so can you provide us a way to conditionally decide whether to  ignore a certain exception or not? Our custom logic for audio might trigger some expected exception from inside exoplayer and we are handling it in the onPlayerError callback. We don't want to skew the stats because of our customization.

Many thanks
Pan

**Comment by jsanford8** [comment]
Great, thanks for the quick response! To be clear, can you confirm that this works correctly for you on 2.4.0? And is there any need for us to fix this to work on 2.3.1 in the immediate future?

We haven't heard that request before, but it's something we should do. Can you let me know how urgent this is? Is this blocking your integration, or is this something that you are looking for for the future?

**Comment by platinum7919** [comment]
```
05-17 08:06:24.875 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: com.charaku.popsical.tv, PID: 6216
                                     java.lang.NoClassDefFoundError: com.mux.stats.sdk.muxstats.b
                                         at com.mux.stats.sdk.muxstats.MuxStats.b(Unknown Source)
                                         at com.mux.stats.sdk.muxstats.MuxStats.<init>(Unknown Source)
                                         at com.charaku.popsical.tv.activity.player.ExoPlayer2Activity.setupMuxStats(ExoPlayer2Activity.java:1152)
                                         at com.charaku.popsical.tv.activity.player.ExoPlayer2Activity.setupMuxStats(ExoPlayer2Activity.java:1144)
```

No, the mux stats SDK doesn't work on 2.4.0 or 2.3.1. And yes, it has been blocking the integration for a few days now. We are currently trying to evaluate and use this SDK since it is one the few in the market that has Exoplayer integration. We even took the effort to upgrade our own exoplayer to 2.4.0 hoping that there will be some update.

Just FYI, you are currently referencing 
`com.google.android.exoplayer2.drm.StreamingDrmSessionManager.EventListener`
in your aar
`com.mux.stats.sdk.muxstats.b` (obviously obfuscated by proguard)

As per [https://medium.com/google-exoplayer/exoplayer-2-2-whats-new-680cab6d9035](url)
> In ExoPlayer 2.2 this functionality is provided directly by the library. StreamingDrmSessionManager has been renamed DefaultDrmSessionManager and now supports modes for acquiring, renewing and releasing offline licenses.

**Comment by theRealWardo** [comment]
this should be resolved with our [v0.0.3 release](https://github.com/muxinc/stats-sdk-exoplayer/releases/tag/v0.0.3). feel free to reopen this issue if you see any issues!
